### ISSUE TITLE
Modify a Validator 

### ISSUE THREAD

**Issue by GreeFine** [mongodb/mongo-rust-driver#1057]
To have a validator set in a collection, I use the [validator](https://docs.rs/mongodb/2.8.2/mongodb/options/struct.CreateCollectionOptions.html#structfield.validator) field in the [CreateCollectionOptions](https://docs.rs/mongodb/2.8.2/mongodb/options/struct.CreateCollectionOptions.html#).

But I need to be able to change the validation schema of an existing collection, and I found no way of doing it. (without dropping and recreating the Collection)

Is there a function/option I didn't find, or is the feature missing ?
If missing, could I propose the feature in a PR, and expect it's to be merged at some time ?

**Comment by abr-egn** [comment]
You're right that the Rust driver doesn't expose a helper method for that; as far as I can tell, drivers for other languages don't either.  It's not part of the MongoDB driver specification, as we generally think of it as an administrative action rather than a client application operation.

That said, you're not the first to ask for this, so I'm going to re-open internal discussion on this :)  While I appreciate the offer of a PR, I don't think we'd be able to accept one for new user-facing API surface.  In the meanwhile, you can use the [run_command](https://docs.rs/mongodb/latest/mongodb/struct.Database.html#method.run_command) method to directly run the `collMod` operation ([example](https://www.mongodb.com/docs/manual/core/schema-validation/update-schema-validation/#modify-the-validation-schema.)).

**Comment by GreeFine** [comment]
Thanks for the example that might work.

I am very surprised by the fact that this isn't something that you already had on the other drivers, makes sense that a new user-facing API needs to be done by your team.

Is there a link to the internal discussion or any resources on this issue ? I am curious as to why it is the case, and also looking for how we should best use the validators.
In our project, we use them to prevent, detect mismatch data exchanged between two crates through the Mongo database, but the data format, schema and thus validator are evolving rapidly, and we want to automatically have the newest validators in place. (a bit like embedded migration for PostgreSQL)
