### ISSUE TITLE
socket_timeout support

### ISSUE THREAD

**Issue by fishincat** [mongodb/mongo-rust-driver#1231]
## Versions/Environment
1. What version of Rust are you using? 
2. What operating system are you using?
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?

## Describe the bug
Is there a plan to support the `socket_timeout` option? Our service has encountered a connection stuck issue. It's nice if this `socket_timeout` options is enabled and will solve our problem.

**Comment by isabelatkinson** [comment]
Hi @fishincat, RUST-564 tracks adding support for this option. It is not currently planned, but I will discuss prioritizing this with the team. Feel free to follow that ticket for more updates.

**Comment by abr-egn** [comment]
We've investigated supporting that option and come to the conclusion that for technical reasons (see #1253 for details) it would require much more engineer time than expected; rather than that, we're going to be moving forward with implementing Client-Side Operation Timeout (see RUST-582) in the coming quarters which will cover this as well as a number of other use cases.
