### ISSUE TITLE
No Error on DNS/network failure

### ISSUE THREAD

**Issue by bbradshaw** [mongodb/mongo-rust-driver#429]
I am getting started with this driver, however I had a difficult time trying to figure out why I was getting no results from a particular query.  I realized later I wasn't connected to the VPN, so the connection should have failed.  This is a minimal reproducible example:

```rust
use mongodb::{Client, Collection};
use mongodb::bson::{doc, Document};
use futures::stream::StreamExt;

#[tokio::main]
async fn main() {
    let client = Client::with_uri_str("mongodb://obvious_garbage").await.unwrap();
    let db = client.database("");
    let collection: Collection<Document> = db.collection("");
    for mut cursor in collection.find(doc!{}, None).await {
        let next = cursor.next().await.unwrap().unwrap();
        println!("{:?}", next);
    }
}
```

My expectation is that this code should panic, either at the creation of the client, or the unwrap() on the result, because there is no such database at mongodb://obvious_garbage.  Instead this code simply runs silently and produces no output.

**Comment by patrickfreed** [comment]
So the reason this behaves the way that it does is that [`std::result::Result` implements `IntoIterator`](https://doc.rust-lang.org/std/result/struct.IntoIter.html) by via an iterator over the `Ok` value (if any), and `Collection::find` returns a `Result<Cursor>`. What's happening here is that `collection.find` is returning `Err(<a server selection error>)` so the `for in` loop doesn't execute its body because there are no `Ok` values to iterate over. If you replace the `for in` loop with `collection.find(doc! {}, None).await.unrwrap()` you should see the error.

Note that async `for in` loops aren't yet a part of the language, so you'll need to use a `while` loop in conjunction with the methods provided by `StreamExt` / `TryStreamExt` to iterate over cursors, like so:
```rust
use mongodb::{Client, Collection};
use mongodb::bson::{doc, Document};
use futures::stream::TryStreamExt;

#[tokio::main]
async fn main() {
    let client = Client::with_uri_str("mongodb://obvious_garbage/?serverSelectionTimeoutMS=1000").await.unwrap();
    let db = client.database("");
    let collection: Collection<Document> = db.collection("");
    let mut cursor = collection.find(doc! {}, None).await.unwrap();
    while let Some(doc) = cursor.try_next().await? {
        println!("{:?}", doc);
    }
}
```
Hope that makes sense; please let us know if you have any further questions!

**Comment by bbradshaw** [comment]
Thanks, that makes sense!
