### ISSUE TITLE
Can't run the documentation examples

### ISSUE THREAD

**Issue by folivi** [mongodb/mongo-rust-driver#463]
Hi, 

i'm trying to use the package and I'm facing some issues. The code below doesn't compile

```
use mongodb::{options::ClientOptions, Client};
#[tokio::main]
async fn main() {
    let mut client_options = ClientOptions::parse("mongodb://localhost:27017").await?;
    let client = Client::with_options(client_options)?;

    for db_name in client.list_database_names(None, None).await? {
        println!("{}", db_name);
    }
    println!("Done");
}

```

I get this error:

```
error: the `?` operator can only be used in an async block that returns `Result` or `Option` (or another type that implements `FromResidual`)
label: this function should return `Result` or `Option` to accept `?`
note: required by `from_residual`
label: this function should return `Result` or `Option` to accept `?`

```

My environment:

Cargo:

```
[dependencies]
mongodb = "2.0.0"
futures = "0.3.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

rustc 1.55.0 (c8dfcfe04 2021-09-06)
```

What I'm I doing wrong?

**Comment by patrickfreed** [comment]
The `?` operator in Rust is a shortcut for returning early when encountering the uncommon path in certain types such as `Result` or `Option`, and it basically de-sugars to the following (for `Result`):
```rust
match result {
    Ok(v) => v,
    Err(e) => return Err(e.into()),
}
```
In this case, you're receiving an error because the `?` operator is used within a function that doesn't return a `Result`, so the `return Err(e.into())` part can't work. If you update the `main` result type to return a `Result`, it should compile.

e.g.
```rust
async fn main() -> mongodb::error::Result<()> {
```
To make error handling much easier to deal with, I highly recommend checking out the [`anyhow`](https://docs.rs/anyhow/1.0.44/anyhow/) crate too.

I hope this helps, please let us know if you have any further questions!
