### ISSUE TITLE
Can't connect to a mongo cluster which address is behind a haproxy.

### ISSUE THREAD

**Issue by WindSoilder** [mongodb/mongo-rust-driver#478]
Reproducing code:
```rust
use mongodb::sync::Client;
use bson::{Document};

fn main() {
    let cli = Client::with_uri_str("mongodb://xxx:xxx@192.168.10.11:37017").unwrap();
    let db = cli.database("local");
    let coll = db.collection::<Document>("oplog.rs");
    println!("{:?}", coll.find_one(None, None).unwrap());
}
```

When I'm trying to find, it returns an error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ServerSelection { message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: 192.168.10.11:37017, Type: Unknown, Error: unexpected end of file }, ] }" }, labels: {} }', src/bin/test.rs:8:48
```

Using pymongo or mongo shell doesn't have this problem:

![图片](https://user-images.githubusercontent.com/22256154/135410521-a1f03bf0-83fa-4ace-8c4b-9c3f3a864f02.png)
The address of mongodb is a haproxy to real mongodb address.  When the ip is not behind a ha proxy, the code works fine.

Database version: 3.2.22

It also seems that the expected tpoplogy type is single:
![图片](https://user-images.githubusercontent.com/22256154/135423896-a5dc9e71-fc68-43bf-9271-b2e8de039a7e.png)

**Comment by WindSoilder** [comment]
Oh, I got the reason, it seems that the driver doesn't support mongodb older than 3.6..... 

A little curious about why ?  It seems that many other drivers support mongodb 3.2+..

**Comment by kmahar** [comment]
Hi @WindSoilder! 

The Rust driver is the newest MongoDB driver, and only did our 1.0 release a little over a year ago. 

From a development perspective, the effort to support server versions both < 3.6 and 3.6+ at once is quite significant due to changes that occurred in 3.6 in how drivers interact with the underlying MongoDB server via the wire protocol, as well as the introduction of sessions support in MongoDB 3.6. I would also note that at the time of our 1.0 release all MongoDB versions < 3.6 had already reached end-of-life. (see: https://www.mongodb.com/support-policy/lifecycles).

Given that, we made the choice to only support 3.6+ and instead focus our development efforts on adding support for newer MongoDB features (e.g. sessions, transactions) along with making the driver performant and addressing the needs of Rust developers through e.g. Serde integration, supporting multiple async runtimes, etc.

**Comment by WindSoilder** [comment]
Oh, I get it, thanks for your detailed explanation, I think it can be closed :-) Thank you.
