### ISSUE TITLE
Where to handle Error "Connection on pool for xxxx cleared because another operation failed with: Broken pipe (os error 32)"

### ISSUE THREAD

**Issue by attliaLin** [mongodb/mongo-rust-driver#507]
I got error likes "Connection on pool for xxxx cleared because another operation failed with: Broken pipe (os error 32)". 

It seems like the connections all cleared. 

I'm trying to recover the connections or just create new connections. I can only find the [CmapEventHandler](https://docs.rs/mongodb/2.0.1/mongodb/event/cmap/trait.CmapEventHandler.html), which doesn't help. 

Any idea?

**Comment by patrickfreed** [comment]
This error is seen when an operation or health check fails in a way that indicates the server in question has gone down and that all the pooled connections have been disconnected, hence the pool being cleared. There isn't a way to recover the cleared connections, but once the server is rediscovered by the monitoring tasks run by the driver, new connections will start to be created.

The `CmapEventHandler` and `SdamEventHandler` can help give an idea as to why a server's pool was cleared, if you need help diagnosing the root cause.

As a side note: if you're running the driver and the server on the same machine, make sure to up the file limit. Sometimes the server can open more files than is allowed, causing it to crash and errors like this to show up in the driver.

**Comment by attliaLin** [comment]
I will try `ulimit`. Thanks!
