### ISSUE TITLE
DBRefs support?

### ISSUE THREAD

**Issue by nasa8x** [mongodb/mongo-rust-driver#514]
Hi, 

I use Mongoose with Node, use populate support DBRefs, so with Rust how should I do the same thing.

Thanks a lot.

**Comment by kmahar** [comment]
Hi @nasa8x, thanks for reaching out!

The Rust driver does not provide a `DBRef` type, however a `DBRef` is really just a MongoDB document with keys named `$ref`, `$id`, and optionally `$db` so if needed you can work with existing data containing DBRefs just by using the `Document` type.

Assuming that the two collections you need to join data from are in the same database, the best way to accomplish something similar to Mongoose's populate functionality in the Rust driver with a single query to get all of the data would be using `aggregate` with `$lookup`.

For example if you have both a `books` and and an `authors` collection:
```rust
let id = ObjectId::new();
db.collection("authors").insert_one(doc! { "name": "Albert Camus", "_id": id }, None).await?;
db.collection("books").insert_one(doc! { "name": "The Stranger", "author_id": id }, None).await?;
let pipeline = vec![doc! {
    "$lookup": {
        "from": "authors",
        "localField": "author_id",
        "foreignField": "_id",
        "as": "authorInfo",
    }
}];
let result = db.collection::<Document>("books").aggregate(pipeline, None).await?;
```
The resulting documents in the cursor (as printed in the MongoDB shell) would be:
```js
[
  {
    _id: ObjectId("6189a602f456a0693242b073"),
    name: 'The Stranger',
    author_id: ObjectId("6189a5b0f456a0693242b072"),
    authorInfo: [
      {
        _id: ObjectId("6189a5b0f456a0693242b072"),
        name: 'Albert Camus'
      }
    ]
  }
]
```

Note that in the above case a manual reference to the `_id` for the author document is used rather than a DBRef, since only the `_id` was needed for my query. However, if the data for the author was stored as a DBRef (in the same database) the same approach would work, you could just reference the `$id` key from the DBRef instead.

If the collections are in separate databases, unfortunately at this point in time `$lookup` would not be an option, and you would need to do two separate queries with e.g. `find` to separately retrieve the documents.

You can see some documentation on the `$lookup` stage [here](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/).

Let me know if that makes sense or if you have further questions!

**Comment by nasa8x** [comment]
@kmahar Very clear, thank you very much.
