### ISSUE TITLE
Async timeouts, multiple async calls

### ISSUE THREAD

**Issue by DebonairFox** [mongodb/mongo-rust-driver#554]
So I am slightly confused by the recommendation to place the async calls in a tokio::task::spawn() thread.
My question is what if I have a function that makes a lot of collection calls, do you recommend placing all the async calls in one tokio spawn()? Or placing every single async call in their own tokio thread?

**Comment by patrickfreed** [comment]
It depends on your use case. If you require timeouts on individual collection calls rather than cumulatively for all of them, then spawning a task per call may be required. Spawning tasks for each could also increase performance if all of them can happen concurrently without issue. One of the benefits of async tasks over standard OS threads is that spawning them is relatively cheap, so spawning a bunch shouldn't be too much of a performance concern (I think).

If the calls need to be done sequentially or if you only care about timing out the collective execution time, then doing them all in one task would be fine.

**Comment by DebonairFox** [comment]
> It depends on your use case. If you require timeouts on individual collection calls rather than cumulatively for all of them, then spawning a task per call may be required. Spawning tasks for each could also increase performance if all of them can happen concurrently without issue. One of the benefits of async tasks over standard OS threads is that spawning them is relatively cheap, so spawning a bunch shouldn't be too much of a performance concern (I think).
> 
> If the calls need to be done sequentially or if you only care about timing out the collective execution time, then doing them all in one task would be fine.

Thank you for the response! Appreciate it
