### ISSUE TITLE
the library doesn't maintain the same cursor when using multiple `mongos` throwing "CursorNotFound"

### ISSUE THREAD

**Issue by dizda** [mongodb/mongo-rust-driver#629]
## Versions/Environment
1. rustc 1.60.0
2. linux
3. mongodb:2.2.0 & bson:2.2.0
4. MongoDB 4.4.10 Community
5. cluster with 3 instances of `mongos`

## Describe the bug
Hey there,

When running a `find_many()` query I regularly get a "CursorNotFound" when paginating over ~200 documents by using a batch of 50 documents.
This is happening when we've increased the `mongos` instances from 1 to 3.
This shouldn't happened unless different TCP connections are being used when paginating from the same cursor, so I guess the cursor can't be found when it goes on a different `mongos` instance.. is this the wanted behavior?

I've tried using sessions which don't help either.
Thank you.

**Comment by patrickfreed** [comment]
Hi @dizda, thanks for reporting this issue!

I haven't been able to reproduce this locally unfortunately, so to confirm this is an issue with the driver, it'd be useful to have a bit more information.
- Can you observe this issue in older versions of the driver? Or did this just start happening in `2.2.0`? This can help us narrow down if this is caused by recent changes or not.
- Are you accessing the mongoses via a proxy / load balancer / through a tunnel? If so, that may be why operations are being routed to the wrong mongos.
- Are you using any other options to your `find` command?
- Do you know the exact number of documents being retrieved?
- Could you provide sample code that demonstrates how you encounter this issue (i.e. constructing the `find` and iterating the cursor)?

Also, to aid in debugging on your end, you can enable command monitoring to see where the commands are being routed to confirm that this is in fact the issue.

Here's some example code that prints out where the `find` and subsequent `getMore` commands for cursors are routed for a given client:
```rust
struct Handler {}

impl CommandEventHandler for Handler {
    fn handle_command_started_event(&self, event: CommandStartedEvent) {
        if event.command_name.as_str() == "getMore" {
            let cursor_id = event.command.get_i64("getMore").unwrap();
            println!("({}) getmore {} => {}", event.request_id, cursor_id, event.connection.address);
        }
    }

    fn handle_command_succeeded_event(&self, event: CommandSucceededEvent) {
        if event.command_name.as_str() == "find" {
            let cursor_id = event.reply.get_document("cursor").unwrap().get_i64("id").unwrap();
            println!("find {} => {}", cursor_id, event.connection.address);
        }
    }

    fn handle_command_failed_event(&self, event: CommandFailedEvent) {
        if event.command_name.as_str() == "getMore" {
            println!("({}) getmore => {} failed", event.request_id, event.connection.address);
        }

    }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let mut options =
        ClientOptions::parse("mongodb://localhost:27017,localhost:27018,localhost:27019/").await?;
    options.command_event_handler = Some(Arc::new(Handler {}));
    let client = Client::with_options(options)?;
    // do stuff with client
    Ok(())
}
```

**Comment by dizda** [comment]
Sorry @patrickfreed, the problem was on our side, we were using only 1 haproxy endpoint with 3 mongos behind rather than specifying directly the 3 mongos IPs (the way you've pointed out).

I can now close this issue.
