### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by ash-hashtag** [mongodb/mongo-rust-driver#697]
The driver also provides a blocking sync API. See the [Installation](https://github.com/mongodb/mongo-rust-driver#enabling-the-sync-api) section for instructions on how to enable it.

The various sync-specific types are found in the mongodb::sync submodule rather than in the crate's top level like in the async API. The sync API calls through to the async API internally though, so it looks and behaves similarly to it.

blocking sync api? internally async? I'm confused a bit
I don't have to worry about blocking thread using sync right?

**Comment by patrickfreed** [comment]
We use the async driver to implement the sync/blocking API, but that's just as a convenience to us so that we don't have to maintain two different drivers.

>I don't have to worry about blocking thread using sync right?

Nope! This concern only applies when using the async driver, since blocking the current thread (as opposed to `await`-ing / yielding the current thread) in an async context can block the progress of all the other async contexts. When using the sync driver however, blocking the current thread only blocks progress of that thread; the other threads can still continue to use the driver.
