### ISSUE TITLE
Cannot execute query in shared library with existing tokio runtime.

### ISSUE THREAD

**Issue by GhostLee** [mongodb/mongo-rust-driver#707]
Cannot execute query in shared library with existing tokio runtime.

## Versions/Environment
1. What version of Rust are you using? 
	`rustc 1.62.0 (a8314ef7d 2022-06-27)`
2. What operating system are you using?
	```
	WindowsBuildLabEx                                       : 19041.1.amd64fre.vb_release.191206-1406
	WindowsCurrentVersion                                   : 6.3
	WindowsEditionId                                        : ProfessionalWorkstation
	WindowsInstallationType                                 : Client
	WindowsProductId                                        : 00391-70000-00000-AA845
	WindowsProductName                                      : Windows 10 Pro for Workstations
	```
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
	```
	https://github.com/rust-lang/crates.io-index#mongodb@2.3.0
	https://github.com/rust-lang/crates.io-index#bson@2.3.0
	```
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
	`5.0.9`
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
	`standalone`

## Describe the bug
	
	When I call the mongo api in shared library with existing tokio runtime created by main executable, it shows error like 
	
	thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ServerSelection { message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: 127.0.0.1:27017, Type: Unknown }, ] }" }, labels: {}, wire_version: None, source: None }', src\lib.rs:67:92
	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
	
	But when I integrated into the same executable, it seems to be working fine.
	I will upload a test package so that you can reproduce the problem.

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening?
	The expected behavior is to get collection name.
* Do you have any particular output that demonstrates this problem?
	At least it should not block the thread, then it should show the collection in my db.
* Do you have any ideas on _why_ this may be happening that could give us a
clue in the right direction?
	Maybe there are some thread local variables?
* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Rust)? 
	Arise out of nowhere
* Are there multiple ways of triggering this bug (perhaps more than one
function produce a crash)?
	Any query function.
* If you know how to reproduce this bug, please include a code snippet here:

	See this: [mongo-bug-fix](https://github.com/GhostLee/mongo-bug-fix)

**To Reproduce**

	You can see README.md to reproduce the bug.

**Comment by patrickfreed** [comment]
Hi @GhostLee, thanks for the detailed reproduction! The repro appears to use [a temporary runtime](https://github.com/GhostLee/mongo-bug-fix/blob/master/fix-plugin/src/lib.rs#L20) to create the client and then another one to execute operations on it. A `Client` cannot be used with multiple different async runtimes though, so this is expected behavior (see [the manual](https://mongodb.github.io/mongo-rust-driver/manual/performance.html#runtime) for some more information). To fix the repro, just use the kernel's runtime to create the client too.

**Comment by GhostLee** [comment]
The temporary runtime is used just to show that the runtime created locally will work fine, you can comment out [the relevant part of the temporary runtime(**Line 22-Line 44**)](https://github.com/GhostLee/mongo-bug-fix/blob/master/fix-plugin/src/lib.rs#L20)) and the error will still be reproduced

**Comment by GhostLee** [comment]
make any progress here?

**Comment by patrickfreed** [comment]
Ah okay, so yeah the issue seems to be what you guessed: tokio (the underlying runtime used by the driver) uses thread local variables which are not being properly shared properly (see https://github.com/tokio-rs/tokio/issues/1964). The MongoDB driver itself doesn't make use of any, so I think this is more of an issue with tokio than with us.
