### ISSUE TITLE
Support for mips

### ISSUE THREAD

**Issue by ykxVK8yL5L** [mongodb/mongo-rust-driver#713]
When i compile my progect for mips-musl and mipsel_musl ,it failed. Because the depence webpki-roots  need  a depence of ring, but the ring doesn't support for mips. So what should i do?

**Comment by abr-egn** [comment]
Unfortunately, we can't remove the dependency on `rustls` (which brings in `ring`) without breaking compatibility; that's a change we have planned for the 3.0 release (which is not currently planned for the short term).

The crate does have support for using `openssl` instead of `rustls`; if openssl supports mips, you might be able to create a working version locally by forking the repo and removing `tls_rustls.rs` and associated dependencies.

**Comment by ykxVK8yL5L** [comment]
> Unfortunately, we can't remove the dependency on `rustls` (which brings in `ring`) without breaking compatibility; that's a change we have planned for the 3.0 release (which is not currently planned for the short term).
> 
> The crate does have support for using `openssl` instead of `rustls`; if openssl supports mips, you might be able to create a working version locally by forking the repo and removing `tls_rustls.rs` and associated dependencies.

Ok I’ll try . Thank you very much.
