### ISSUE TITLE
Collection watch doesn't work when called after tokio::spawn

### ISSUE THREAD

**Issue by LukasDeco** [mongodb/mongo-rust-driver#784]
## Versions/Environment
1. What version of Rust are you using?  - 1.65.0
2. What operating system are you using? - WSL (Linux on windows)
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`) - mongodb@2.3.1 & bson@2.4.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`)  - 5.0.14
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? - Replica Set - 3 nodes

## Describe the bug
When I call `Collection.watch` directly inside the main function, everything works fine. But, when I call `Collection.watch` INSIDE of a `tokio::task::spawn` it gives me this error:
```
 Error { kind: ServerSelection { message: "Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: cluster0-shard-00-02-pn2t1.mongodb.net:27017, Type: Unknown }, { Address: cluster0-shard-00-01-pn2t1.mongodb.net:27017, Type: Unknown }, { Address: cluster0-shard-00-00-pn2t1.mongodb.net:27017, Type: Unknown }, ] }" }, labels: {}, wire_version: None, source: None }

```

Here is main.rs:

```
async fn main() {
    let mongo_uri = env::var("MONGO_URI").unwrap_or_default();

    // Parse your connection string into an options struct
    let client_options = ClientOptions::parse(mongo_uri).await.unwrap();

    // Get a handle to the cluster
    let client = Client::with_options(client_options).unwrap();
    // Ping the server to see if you can connect to the cluster
    println!("Connected successfully.");

    // List the names of the databases in that cluster
    tokio::spawn(events::notifications::process_events(client));
}
```

and here is process_events:
```
pub async fn process_events(client: Client) {
    let occasionally_db = client.database("Occasionally");
    let notifications_collection = occasionally_db.collection::<Document>("Notifications");
    let change_stream_result = notifications_collection.watch(None, None).await;
    let mut change_stream = match change_stream_result {
        Ok(change_stream) => change_stream,
        Err(err) => panic!("Oh no an error! {}", err),
    };
    while let Some(event) = change_stream.next_if_any().await.transpose() {
        match event {
            Ok(event) => println!(
                "operation performed: {:?}, document: {:?}",
                event.operation_type, event.full_document
            ),
            Err(e) => println!("Err: {}", e),
        }
        // operation performed: Insert, document: Some(Document({"x": Int32(1)}))
    }
}

```

I've tried multiple different ways. Using `async move{}` to wrap the function in main.rs doesn't make a difference either.

I am very new to rust so possibly I am missing something, but I've followed along other examples, and it doesn't seem like there should be a problem with doing this.

Please let me know if you have more questions, and thanks!

**Comment by kmahar** [comment]
Hi @LukasDeco, thanks for getting in touch.

I was able to reproduce this locally and I believe I understand what is happening here. 

Some relevant background context: when a `Client` is first created, it will make an initial assumption about your topology type based on the connection string. In this case, I am guessing your connection string uses the `replicaSet` option? Which leads the driver to set its initial view of the topology to `ReplicaSetNoPrimary` with three servers of unknown type, like that shown in the error message you included. Now, typically what happens next is that the driver starts up background tasks that determine the actual types of the members in your replica set (primary vs. secondary vs. arbiter) and then continue to run for the lifetime of your application and monitor the hosts for any changes, so that e.g. if a server goes down the driver knows not to route commands to it. 

I think what is happening here is as follows:
1) Once the `main` function exits, although your spawned task is still executing, the Tokio runtime begins to shut down. 
2) Since the `main` function exits almost immediately after creating the `Client`, the client does not get a chance to spawn its monitoring tasks before runtime shutdown starts. And once a tokio runtime starts shutting down, new tasks cannot be spawned.
3) Since the monitoring tasks never make progress, the `Client` never discovers the type of any of the servers in the topology, and so none of them are deemed suitable to send a command to and open a change stream on.
4) After the 30s default server selection timeout is hit, the driver throws the error you include above.

In general, we can't make any guarantees that a `Client` will behave correctly once the Tokio runtime starts to shut down, since Tokio does not guarantee spawned tasks will complete following shutdown - from the [docs for `tokio::spawn`](https://docs.rs/tokio/latest/tokio/fn.spawn.html):
> There is no guarantee that a spawned task will execute to completion. When a runtime is shutdown, all outstanding tasks are dropped, regardless of the lifecycle of that task.

What I would suggest here is to implement some sort of graceful shutdown here so that you can coordinate between your `main` function exiting and the work going on in your `process_events` task. 
You might find [this page](https://tokio.rs/tokio/topics/shutdown) on Tokio graceful shutdown helpful. For example, one option here would be to have your `main` function listen for a ctrl+c shutdown signal, and when it receives one, use a broadcast channel that `process_events` listens on to tell that function to exit early so the task can exit. Alternatively, if you want your program to keep running until `change_stream.next_if_any()` returns `None`, you could `await` the `JoinHandle` that `tokio::spawn` returns as you create the child task. 

I hope that makes sense, please feel free to follow up with any questions!

**Comment by LukasDeco** [comment]
Thanks @kmahar for the helpful explanation! I'll try that out.

**Comment by LukasDeco** [comment]
For the record I am now using futures::future::join() which seems to work along with running a server:
```
futures::future::join(
        events::notifications::new_insert_change_stream(&mut &client, &sms_messaging_service),
        start_server(),
    )
    .await;
```

I think this can maybe be improved upon by using multiple threads but that's for later.
