### ISSUE TITLE
RUST-1651 Make `FilesCollectionDocument` generic over `metadata` field type

### ISSUE THREAD

**Issue by Logarithmus** [mongodb/mongo-rust-driver#868]
Currently it unconditionally deserializes `metadata` into `bson::Document`, and then a developer has to convert it to custom struct to actually work with. This incurs overhead of intermediate `bson::Document`. Would be nice to make it generic, so that `mongodb` would deserialize `metadata` field into the desired struct directly, just like it happens with `Collection::<T>::find_one(..)`.
I understand it looks like a breaking change, which may be a problem...

**Comment by isabelatkinson** [comment]
Hi @Logarithmus, thanks for filing this issue! We agree that making the `metadata` field generic would be a useful update to the `FilesCollectionDocument` type; however, we're unable to make breaking changes in our API until the next major version release. We do not currently have a timeline for a 3.0.0 release, but I've filed RUST-1651 to consider this change when we do get to it.

**Comment by isabelatkinson** [comment]
Hey @Logarithmus, we've decided not to do this because of the impacts that a generic type on `FilesCollectionDocument` would have on the other types that store it. See RUST-1651 for more details. I'm going to close this out, but feel free to open a new issue if you have any further questions or feedback!
