### ISSUE TITLE
Is there any way we can pass `tlsCertificateKeyFilePassword ` for x.509 authentication?

### ISSUE THREAD

**Issue by prabhugopal** [mongodb/mongo-rust-driver#988]
## Versions/Environment
1. What version of Rust are you using?  2.7.1

I have read here https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.tlsCertificateKeyFilePassword that `tlsCertificateKeyFilePassword` is not supported for some of the drivers. 

Any reason for not supporting it? Any plans to enable in near future? 

These would help me to decide on alternative. Appreciate your input.

**Comment by isabelatkinson** [comment]
Hi @prabhugopal, thanks for opening this issue! I've left a comment indicating `tlsCertificateKeyFilePassword` has been requested on RUST-226, which is the ticket we currently have open to track supporting this option. This is likely something we won't be able to get to in the near future because of the complications I've outlined in the comment, but feel free to follow along there for updates. Please let me know if you have any further questions or requests!
